server.name: kibana
server.host: "0"
server.basePath: "/kibana"
server.rewriteBasePath: true
elasticsearch.url: http://elasticsearch:9200
kibana.defaultAppId: "dashboard/JKA"
console.enabled: false
timelion.enabled: false
xpack.apm.enabled: false
xpack.canvas.enabled: false
xpack.graph.enabled: false
xpack.grokdebugger.enabled: false
xpack.infra.sources.default.logAlias: "logstash-*"
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.reporting.enabled: false
xpack.searchprofiler.enabled: false
